CREATE TABLE proyectos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(150) NOT NULL,
    descripcion    TEXT,
    propietario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE
);

CREATE INDEX idx_proyectos_propietario_id ON proyectos(propietario_id);