CREATE TABLE tareas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(150) NOT NULL,
    descripcion    TEXT,
    estado         VARCHAR(20)  NOT NULL,
    proyecto_id    BIGINT NOT NULL REFERENCES proyectos(id) ON DELETE CASCADE,
    asignado_a_id  BIGINT REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE INDEX idx_tareas_proyecto_id ON tareas(proyecto_id);
CREATE INDEX idx_tareas_asignado_a_id ON tareas(asignado_a_id);