spring.application.name=demo
scalar.enabled=true
scalar.path=/scalar

# Conexion a la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon_bd
spring.datasource.username=pokemon_user
spring.datasource.password=pokemon_pass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
