spring.application.name=demo
scalar.enabled=true
scalar.path=/scalar

# Conexion a la BD
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion-tareas_db
spring.datasource.username=postgres
spring.datasource.password=Admin123456
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

# clave secreta del jwt
app.jwt.secret=una_clave_secreta_de_al_menos_32_caracteres_para_HS256
app.jwt.expiration-ms=3600000